# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='extended', to='sites.Site', verbose_name='Site')),
            ],
            options={
                'db_table': 'django_site_extended',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('css_classes', models.CharField(max_length=200, verbose_name='CSS classes')),
                ('extended_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='sites.Site', verbose_name='Site')),
            ],
            options={
                'db_table': 'django_site_social_network',
            },
        ),
    ]
