# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 21:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0013_urlconfrevision'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('default_meta_description', models.TextField(blank=True, help_text='The default text displayed in search engines.', max_length=255, null=True, verbose_name='default description')),
                ('copyright', models.TextField(blank=True, max_length=255, null=True, verbose_name='copyright')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='sites.Site', verbose_name='Site')),
            ],
            options={
                'db_table': 'djangocms_ztheme_site_extra',
            },
        ),
        migrations.CreateModel(
            name='SiteSocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name is used for CSS classes.', max_length=255, verbose_name='name')),
                ('url', models.CharField(max_length=2048, verbose_name='url')),
                ('top_menu', models.BooleanField(default=False, verbose_name='top menu')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='sites.Site', verbose_name='Site')),
            ],
            options={
                'db_table': 'djangocms_ztheme_site_social_network',
            },
        ),
        migrations.CreateModel(
            name='ZThemeColumn',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('xs_columns', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='columns')),
                ('xs_offset', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='offset')),
                ('xs_push', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='push')),
                ('xs_pull', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='pull')),
                ('sm_columns', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='columns')),
                ('sm_offset', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='offset')),
                ('sm_push', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='push')),
                ('sm_pull', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='pull')),
                ('md_columns', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='columns')),
                ('md_offset', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='offset')),
                ('md_push', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='push')),
                ('md_pull', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='pull')),
                ('lg_columns', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='columns')),
                ('lg_offset', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='offset')),
                ('lg_push', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='push')),
                ('lg_pull', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='pull')),
                ('extra_css_classes', models.CharField(blank=True, help_text='Extra CSS classes for HTML tag.', max_length=255, null=True, verbose_name='extra css classes')),
            ],
            options={
                'db_table': 'djangocms_ztheme_column',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ZThemeRow',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('extra_css_classes', models.CharField(blank=True, help_text='Extra CSS classes for HTML tag.', max_length=255, null=True, verbose_name='extra css classes')),
            ],
            options={
                'db_table': 'djangocms_ztheme_row',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ZThemeSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('top', models.BooleanField(default=False, verbose_name='top')),
                ('xs', models.BooleanField(default=False, verbose_name='extra small devices')),
                ('sm', models.BooleanField(default=False, verbose_name='small devices')),
                ('md', models.BooleanField(default=False, verbose_name='medium devices')),
                ('lg', models.BooleanField(default=False, verbose_name='large devices')),
                ('extra_css_classes', models.CharField(blank=True, help_text='Extra CSS classes for HTML tag.', max_length=255, null=True, verbose_name='extra css classes')),
            ],
            options={
                'db_table': 'djangocms_ztheme_section',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ZThemeSectionCallTo',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('fa_icon', models.CharField(max_length=255, verbose_name='font awesome icon')),
                ('link_text', models.CharField(max_length=255, verbose_name='link text')),
                ('url', models.CharField(max_length=2048, verbose_name='url')),
                ('extra_css_classes', models.CharField(blank=True, help_text='Extra CSS classes for HTML tag.', max_length=255, null=True, verbose_name='extra css classes')),
            ],
            options={
                'db_table': 'djangocms_ztheme_section_callto',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ZThemeSectionFeature',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('fa_icon', models.CharField(max_length=255, verbose_name='font awesome icon')),
                ('description', models.TextField(blank=True, max_length=2048, null=True, verbose_name='description')),
            ],
            options={
                'db_table': 'djangocms_ztheme_section_feature',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ZThemeSectionFeatures',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('extra_css_classes', models.CharField(blank=True, help_text='Extra CSS classes for HTML tag.', max_length=255, null=True, verbose_name='extra css classes')),
            ],
            options={
                'db_table': 'djangocms_ztheme_section_features',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
