# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('default_meta_description', models.TextField(blank=True, help_text='The default text displayed in search engines.', max_length=255, null=True, verbose_name='default description')),
                ('copyright', models.TextField(blank=True, max_length=255, null=True, verbose_name='copyright')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='sites.Site', verbose_name='Site')),
            ],
            options={
                'db_table': 'djangocms_ztheme_site_extra',
            },
        ),
        migrations.CreateModel(
            name='SiteSocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='email')),
                ('url', models.CharField(max_length=2048, verbose_name='url')),
                ('css_classes', models.CharField(blank=True, help_text='Extra CSS classes for <a> HTML tag.', max_length=255, null=True, verbose_name='css classes')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='sites.Site', verbose_name='Site')),
            ],
            options={
                'db_table': 'djangocms_ztheme_site_social_network',
            },
        ),
    ]
