# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_ztheme', '0002_auto_20160417_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zthemecolumn',
            old_name='lg_devices',
            new_name='lg_columns',
        ),
        migrations.RenameField(
            model_name='zthemecolumn',
            old_name='md',
            new_name='md_columns',
        ),
        migrations.RenameField(
            model_name='zthemecolumn',
            old_name='sm',
            new_name='sm_columns',
        ),
        migrations.RenameField(
            model_name='zthemecolumn',
            old_name='xs',
            new_name='xs_columns',
        ),
    ]
