# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 21:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_ztheme', '0003_auto_20160417_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesocialnetwork',
            name='css_classes',
        ),
        migrations.AddField(
            model_name='sitesocialnetwork',
            name='top_menu',
            field=models.BooleanField(default=False, verbose_name='top menu'),
        ),
        migrations.AlterField(
            model_name='sitesocialnetwork',
            name='name',
            field=models.CharField(help_text='Name is used for CSS classes.', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='zthemecolumn',
            name='lg_columns',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='columns'),
        ),
        migrations.AlterField(
            model_name='zthemecolumn',
            name='lg_offset',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='offset'),
        ),
        migrations.AlterField(
            model_name='zthemecolumn',
            name='lg_pull',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='pull'),
        ),
        migrations.AlterField(
            model_name='zthemecolumn',
            name='lg_push',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='push'),
        ),
        migrations.AlterField(
            model_name='zthemecolumn',
            name='md_columns',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='columns'),
        ),
        migrations.AlterField(
            model_name='zthemecolumn',
            name='md_offset',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='offset'),
        ),
        migrations.AlterField(
            model_name='zthemecolumn',
            name='md_pull',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='pull'),
        ),
        migrations.AlterField(
            model_name='zthemecolumn',
            name='md_push',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='push'),
        ),
        migrations.AlterField(
            model_name='zthemecolumn',
            name='sm_columns',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='columns'),
        ),
        migrations.AlterField(
            model_name='zthemecolumn',
            name='sm_offset',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='offset'),
        ),
        migrations.AlterField(
            model_name='zthemecolumn',
            name='sm_pull',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='pull'),
        ),
        migrations.AlterField(
            model_name='zthemecolumn',
            name='sm_push',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='push'),
        ),
        migrations.AlterField(
            model_name='zthemecolumn',
            name='xs_columns',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='columns'),
        ),
        migrations.AlterField(
            model_name='zthemecolumn',
            name='xs_offset',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='offset'),
        ),
        migrations.AlterField(
            model_name='zthemecolumn',
            name='xs_pull',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='pull'),
        ),
        migrations.AlterField(
            model_name='zthemecolumn',
            name='xs_push',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='push'),
        ),
    ]
