# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_urlconfrevision'),
        ('djangocms_ztheme', '0004_auto_20160418_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZThemeRow',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('extra_css_classes', models.CharField(blank=True, help_text='Extra CSS classes for HTML tag.', max_length=255, null=True, verbose_name='extra css classes')),
            ],
            options={
                'db_table': 'djangocms_ztheme_row',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='zthemecolumn',
            name='extra_css_classes',
            field=models.CharField(blank=True, help_text='Extra CSS classes for HTML tag.', max_length=255, null=True, verbose_name='extra css classes'),
        ),
    ]
