# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_urlconfrevision'),
        ('djangocms_ztheme', '0006_zthemesectioncallto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZThemeSectionFeature',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('fa_icon', models.CharField(max_length=255, verbose_name='font awesome icon')),
                ('description', models.TextField(blank=True, max_length=2048, null=True, verbose_name='description')),
            ],
            options={
                'db_table': 'djangocms_ztheme_section_feature',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
