---

- name: Provisioning with debops
  become: True
  hosts: all

  roles:
    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]
      apt_preferences_dependent_list:
        - '{{ sshd_apt_preferences_dependent_list }}'

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm_dependent_rules:
        - '{{ sshd_ferm_dependent_rules }}'

    - role: debops.tcpwrappers
      tags: [ 'role::tcpwrappers' ]
      tcpwrappers_dependent_allow:
        - '{{ sshd_tcpwrappers_dependent_allow }}'

    - role: debops.sshd
      sshd_host_allow_groups: [ 'vagrant' ]
      tags: [ 'role::sshd' ]

    - role: debops.mariadb_server
      mariadb_server_bind_address: '::'
      tags: [ 'role::mariadb_server' ]

    - role: debops.mariadb
      mariadb_databases:
        - name: 'anticapimu'
      mariadb_users:
        - name: 'anticapimu'
          password: 'anticapimu'
          host: '%'
      tags: [ 'role::mariadb' ]
